### PR TITLE
Extract core functionality to HockeyAppAndroidEngine class

### PR DESCRIPTION
**Pull request by jrftrifork**
This leaves HockeyAppAndroid only as a bridge between the MonoBehaviour Life cycle and ability to start coroutines.

The motivation for this change is our integration of HockeyApp into an app where the exact configuration (app id's, app distribution and so on) depends on factors that are only known at runtime, and after the HockeyAppAndroid MonoBehaviour has initialized itself with the static configuration from the prefab.

The inclusion of this pull request would be very beneficial for us and should cause no interface changes to existing apps.

### CODE REVIEW

**Comment by jrftrifork** [comment]
If it's inconvenient to have to change the installation to copy two CS files to the Unity project, HockeyAppAndroid and HockeyAppAndroidEngine can be combined into the HockeyAppAndroid.cs file.

**Comment by chrwend** [comment]
Hi @jrftrifork,

first and foremost thanks for the contribution. Could you please give me some further info about how you are using this class in your scenario? I assume that you are creating an instance of the engine directly in code rather than using the behaviour, am I right?

**Comment by jrftrifork** [comment]
Hi Christoph - @chrwend,

The app we are integrating is more in the enterprise area than most Unity based apps. The usage pattern is, that we have a central MonoBehaviour, that "wakes up" (in Awake) and determines among other things the correct configuration for the specific app variant and the current user.

By the time that has been determined, the standard HockeyApp MonoBehaviour will have woken up and begun initializing things that might not be wanted. Your assumption is absolutely correct, we solve this by not having the MonoBehaviour attached to a game object in the scene, but instantiating it from one of our own MonoBehaviours.

We know that down the road, we will need to submit some kind of user/device identifaction together with each recorded crash, so we will be needing something like the CrashManagerListener from the native Android SDK. As I see it, making the instantiation programmatic is the easiest way to achieve this.

I hope this clarifies the needs we have, if not feel free to ask for a more thorough description

**Comment by TroubleMakerBen** [comment]
Hi everyone,
we are not going to accept this any time soon and as the PR is very old, I'll simply close it.
Thanks for the insights and discussion and, of course, thanks for using HockeyApp!

**Pull request closed without merging**
